#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no-install commitlint --edit ""

#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run pre-commit


#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run post-merge
